### ISSUE TITLE
uninitialized variable

### ISSUE THREAD

**Issue by maddin200** [cdalitz/triplclust#5]
cluster.cpp line 71
Code:
hclust_fast_methods link; // <-- not initialized in every path
  if (!triplet_size) {
    // if no triplets are generated
    return;
  }
  // choose linkage method
  switch (method) {
    case SINGLE:
      link = HCLUST_METHOD_SINGLE;
      break;
    case COMPLETE:
      link = HCLUST_METHOD_COMPLETE;
      break;
    case AVERAGE:
      link = HCLUST_METHOD_AVERAGE;
      break;
  }

**Comment by cdalitz** [comment]
According to the `enum` defined in `util.h`, the variable *method* (which is of type `Linkage`) can only be one of *SINGLE*, *COMPLETE*, or *AVERAGE*. Can you please explain which case is lacking?

**Comment by maddin200** [comment]
Maybe I am wrong - but HCLUST_METHOD_MEDIAN missing ?

**Comment by cdalitz** [comment]
Although the *fastcluster* package provides more linkage methods, *triplclust* only offers three methods, which are defined in the `enum Linkage` in `util.h`. Ig you call *triplclust* without any argument, you ontian a usage method which also lists the three supported methods.

Actually, the TriplClust algortihm as described in the IPOL paper only makes sense with a SINGLE LINK clustering, and it is thus pointless to add more (useless) alternatives.
